# container-based build
sudo: false

language: scala

env:
  - JAVA_OPTS="-DSKIP_FLAKY=true -Dsbt.log.noformat=true"

# These directories are cached to S3 at the end of the build
cache:
  directories:
   - $HOME/.ivy2
   - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION
   - $HOME/.dodo

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

scala:
  - 2.11.11
  - 2.12.4

jdk:
  - oraclejdk8

notifications:
  hipchat:
    rooms:
      secure: ip7yYXJllgMZEwkDNgEfcFUmVtJlGzW3eC+x/NHZWUe7aFTbD/+Who31EWLU28fU9O9FdQquzL96oEQMyD+d+Cy03EhboOJf1f/oKinT1UXNvcx+kf912EgaU8ei4ZQ/o5oc7A+sTyq3wA/FSm/BwhUOjSDFZ4oOTZZXxoZYvYc=

before_script:
  # default $SBT_OPTS is irrelevant to sbt lancher
  - unset SBT_OPTS
  - travis_retry ./sbt --error ++$TRAVIS_SCALA_VERSION update

script:
    - travis_retry ./sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport
    - travis_retry ./sbt ++2.11.11 "project util-intellij" coverage test coverageReport
    - ./sbt ++$TRAVIS_SCALA_VERSION coverageAggregate

after_success:
    - bash <(curl -s https://codecov.io/bash)
